-- Drop existing table if it exists to ensure a clean slate.
DROP TABLE IF EXISTS public.inbound_documents;

-- Create the inbound_documents table
CREATE TABLE public.inbound_documents (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    reference text NULL,
    date timestamp with time zone NULL,
    received_by text NULL,
    sku text NULL,
    barcode text NULL,
    name text NULL,
    brand text NULL,
    exp_date date NULL,
    qty integer NULL,
    main_status text NULL,
    CONSTRAINT inbound_documents_pkey PRIMARY KEY (id)
);

-- Optional: Add indexes for faster queries on frequently searched columns
CREATE INDEX idx_inbound_reference ON public.inbound_documents (reference);
CREATE INDEX idx_inbound_sku ON public.inbound_documents (sku);
CREATE INDEX idx_inbound_barcode ON public.inbound_documents (barcode);

-- Optional: Enable Row Level Security (RLS) if you plan to use it
-- ALTER TABLE public.inbound_documents ENABLE ROW LEVEL SECURITY;
