-- Create the inbound_documents table
CREATE TABLE
  public.inbound_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    reference TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    received_by TEXT NOT NULL,
    sku TEXT NOT NULL,
    barcode TEXT NOT NULL,
    brand TEXT,
    exp_date DATE,
    qty INTEGER NOT NULL,
    main_status TEXT DEFAULT 'Assign'::TEXT,
    CONSTRAINT inbound_documents_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

-- Optional: Add indexes for better query performance
CREATE INDEX idx_inbound_reference ON public.inbound_documents USING btree (reference);
CREATE INDEX idx_inbound_sku ON public.inbound_documents USING btree (sku);
CREATE INDEX idx_inbound_barcode ON public.inbound_documents USING btree (barcode);
