-- 1. Hentikan semua koneksi aktif ke database
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres';

-- 2. Hapus tabel yang sudah ada jika ada (PERHATIAN: Ini akan menghapus semua data di dalamnya)
DROP TABLE IF EXISTS public.marketplace_stores;
DROP TABLE IF EXISTS public.admin_tasks;

-- 3. Buat ulang tabel 'admin_tasks'
CREATE TABLE public.admin_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    job TEXT NOT NULL,
    shift TEXT NOT NULL,
    status TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 4. Buat ulang tabel 'marketplace_stores' dengan tiga kolom
CREATE TABLE public.marketplace_stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_name TEXT,
    store_name TEXT,
    platform TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. Aktifkan Row Level Security (RLS) untuk kedua tabel
ALTER TABLE public.admin_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_stores ENABLE ROW LEVEL SECURITY;

-- 6. Buat kebijakan (Policies) untuk 'admin_tasks'
-- Izinkan semua aksi (SELECT, INSERT, UPDATE, DELETE) untuk pengguna yang terautentikasi
CREATE POLICY "Allow all access for authenticated users on admin_tasks"
ON public.admin_tasks
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 7. Buat kebijakan (Policies) untuk 'marketplace_stores'
-- Izinkan semua aksi (SELECT, INSERT, UPDATE, DELETE) untuk pengguna yang terautentikasi
CREATE POLICY "Allow all access for authenticated users on marketplace_stores"
ON public.marketplace_stores
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Pesan: Skrip selesai. Tabel telah dibuat ulang dan RLS telah diaktifkan dengan kebijakan keamanan dasar.
