-- Skrip ini akan membuat tabel 'marketplace_stores' dengan struktur yang benar
-- dan menerapkan Row Level Security (RLS) untuk keamanan.
-- Jalankan skrip ini di SQL Editor pada dashboard Supabase Anda.

-- 1. Buat tabel 'marketplace_stores' jika belum ada
CREATE TABLE IF NOT EXISTS public.marketplace_stores (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    marketplace_name text,
    store_name text,
    platform text,
    CONSTRAINT marketplace_stores_pkey PRIMARY KEY (id)
);

-- 2. Aktifkan Row Level Security (RLS) pada tabel. Ini penting untuk keamanan.
ALTER TABLE public.marketplace_stores ENABLE ROW LEVEL SECURITY;

-- 3. Hapus kebijakan (policies) lama jika ada untuk menghindari konflik.
DROP POLICY IF EXISTS "Allow public read access" ON public.marketplace_stores;
DROP POLICY IF EXISTS "Allow authenticated users to manage stores" ON public.marketplace_stores;


-- 4. Buat kebijakan keamanan baru.
-- Kebijakan ini mengizinkan pengguna yang sudah login (authenticated)
-- untuk melakukan semua aksi (SELECT, INSERT, UPDATE, DELETE).
CREATE POLICY "Allow authenticated users to manage stores"
ON public.marketplace_stores
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 5. Beri tahu Supabase untuk memuat ulang skema setelah perubahan.
NOTIFY pgrst, 'reload schema';
