-- Create the menu_permissions table
CREATE TABLE IF NOT EXISTS public.menu_permissions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    menu_href character varying NOT NULL,
    is_accessible boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT menu_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT menu_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT menu_permissions_user_id_menu_href_key UNIQUE (user_id, menu_href)
);

-- Enable Row Level Security
ALTER TABLE public.menu_permissions ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read and manage permissions
CREATE POLICY "Allow authenticated users to read permissions"
    ON public.menu_permissions
    FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to manage permissions"
    ON public.menu_permissions
    FOR ALL
    USING (auth.role() = 'authenticated');

-- Notify Supabase of the new table
NOTIFY pgrst, 'reload schema';
